services:
  - type: web
    name: maritime-event-extractor
    runtime: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///instance/sof_extractor.db
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
